export const ADD_USER = "ADD_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";

export const ADD_PANTRY_ITEM = "ADD_PANTRY_ITEM";
export const UPDATE_PANTRY_ITEM = "UPDATE_PANTRY_ITEM";
export const DELETE_PANTRY_ITEM = "DELETE_PANTRY_ITEM";

export const ADD_DIETARY_PREFERENCE = "ADD_DIETARY_PREFERENCE";
export const UPDATE_DIETARY_PREFERENCE = "UPDATE_DIETARY_PREFERENCE";
export const DELETE_DIETARY_PREFERENCE = "DELETE_DIETARY_PREFERENCE";
export const ADD_ALLERGY = "ADD_ALLERGY";
export const DELETE_ALLERGY = "DELETE_ALLERGY";

export const SAVE_RECIPE = "SAVE_RECIPE";
export const UNSAVE_RECIPE = "UNSAVE_RECIPE";

export const SET_SCREEN_MODE = "SET_SCREEN_MODE";

export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
